version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine3.18
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./game/:/usr/share/nginx/html/pacman:ro
    restart: always